package Entidades;
// Generated 28-feb-2019 17:26:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aspirante generated by hbm2java
 */
public class Aspirante  implements java.io.Serializable {

    private String msj;
    private Integer ed;

    public Integer getEd() {
        return ed;
    }

    public void setEd(Integer ed) {
        this.ed = ed;
    }
    
    
    

    public String getMsj() {
        return msj;
    }

    public void setMsj(String msj) {
        this.msj = msj;
    }
    
    
    

     private Integer idAspirante;
     private Categoria categoria;
     private Escuela escuela;
     private String apellido;
     private String nombre;
     private String edad;
     private char sexo;
     private String direccion;
     private Integer dni;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Aspirante() {
    }

	
    public Aspirante(Categoria categoria, Escuela escuela, String nombre, String edad, char sexo) {
        this.categoria = categoria;
        this.escuela = escuela;
        this.nombre = nombre;
        this.edad = edad;
        this.sexo = sexo;
    }
    public Aspirante(Categoria categoria, Escuela escuela, String apellido, String nombre, String edad, char sexo, String direccion, Integer dni, Set<Inscripcion> inscripcions) {
       this.categoria = categoria;
       this.escuela = escuela;
       this.apellido = apellido;
       this.nombre = nombre;
       this.edad = edad;
       this.sexo = sexo;
       this.direccion = direccion;
       this.dni = dni;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdAspirante() {
        return this.idAspirante;
    }
    
    public void setIdAspirante(Integer idAspirante) {
        this.idAspirante = idAspirante;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


