package Entidades;
// Generated 28-feb-2019 17:26:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombre;
     private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);

    public Categoria() {
    }

	
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, Set<Aspirante> aspirantes) {
       this.nombre = nombre;
       this.aspirantes = aspirantes;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Aspirante> getAspirantes() {
        return this.aspirantes;
    }
    
    public void setAspirantes(Set<Aspirante> aspirantes) {
        this.aspirantes = aspirantes;
    }




}


