package Entidades;
// Generated 28-feb-2019 17:26:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Competencia generated by hbm2java
 */
public class Competencia  implements java.io.Serializable {


     private Integer idcompetencia;
     private String nombre;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Competencia() {
    }

	
    public Competencia(String nombre) {
        this.nombre = nombre;
    }
    public Competencia(String nombre, Set<Inscripcion> inscripcions) {
       this.nombre = nombre;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdcompetencia() {
        return this.idcompetencia;
    }
    
    public void setIdcompetencia(Integer idcompetencia) {
        this.idcompetencia = idcompetencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


