package Entidades;
// Generated 28-feb-2019 17:26:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private Integer idEscuela;
     private String nombre;
     private String direccion;
     private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);

    public Escuela() {
    }

	
    public Escuela(String nombre) {
        this.nombre = nombre;
    }
    public Escuela(String nombre, String direccion, Set<Aspirante> aspirantes) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.aspirantes = aspirantes;
    }
   
    public Integer getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(Integer idEscuela) {
        this.idEscuela = idEscuela;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Aspirante> getAspirantes() {
        return this.aspirantes;
    }
    
    public void setAspirantes(Set<Aspirante> aspirantes) {
        this.aspirantes = aspirantes;
    }




}


