package Entidades;
// Generated 28-feb-2019 17:26:11 by Hibernate Tools 4.3.1



/**
 * InscripcionId generated by hbm2java
 */
public class InscripcionId  implements java.io.Serializable {


     private int idaspirante;
     private int idcompetencia;

    public InscripcionId() {
    }

    public InscripcionId(int idaspirante, int idcompetencia) {
       this.idaspirante = idaspirante;
       this.idcompetencia = idcompetencia;
    }
   
    public int getIdaspirante() {
        return this.idaspirante;
    }
    
    public void setIdaspirante(int idaspirante) {
        this.idaspirante = idaspirante;
    }
    public int getIdcompetencia() {
        return this.idcompetencia;
    }
    
    public void setIdcompetencia(int idcompetencia) {
        this.idcompetencia = idcompetencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InscripcionId) ) return false;
		 InscripcionId castOther = ( InscripcionId ) other; 
         
		 return (this.getIdaspirante()==castOther.getIdaspirante())
 && (this.getIdcompetencia()==castOther.getIdcompetencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdaspirante();
         result = 37 * result + this.getIdcompetencia();
         return result;
   }   


}


