/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.CeldaCheck;
import Interfaces.IComunicar;
import Clases.RenderCheck;
import Controladores.ControladorFrmRegistrarIncripciones;
import Controladores.EscuelaDatos;
import Entidades.Aspirante;
import Entidades.Competencia;
import Entidades.Escuela;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Familia
 */
public class frmRegistrarInscripciones extends javax.swing.JFrame implements IComunicar{

    ControladorFrmRegistrarIncripciones _controladorFrm;
    private TableRowSorter trsfiltro;
    String filtro;
    
    /**
     * Creates new form frmRegistrarInscripciones
     */
    public frmRegistrarInscripciones() {
        initComponents();
        
       jpEscuela.setBorder(javax.swing.BorderFactory.createTitledBorder("Escuelas"));
//        jPanelAspirantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Aspirantes"));
//        jPanelCompetencias.setBorder(javax.swing.BorderFactory.createTitledBorder("Competencias"));
//        jPanelCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorías"));






    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEscuela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEscuelas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCompetencias = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLCategorias = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtAspirantes = new javax.swing.JTable();
        btnAgregarAspirante = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpEscuela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableEscuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEscuelas);

        jLabel1.setText("Filtrar");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpEscuelaLayout = new javax.swing.GroupLayout(jpEscuela);
        jpEscuela.setLayout(jpEscuelaLayout);
        jpEscuelaLayout.setHorizontalGroup(
            jpEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscuelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpEscuelaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpEscuelaLayout.setVerticalGroup(
            jpEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscuelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEscuelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtCompetencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtCompetencias);

        jScrollPane2.setViewportView(jLCategorias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtAspirantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtAspirantes);

        btnAgregarAspirante.setText("Nuevo aspirante");
        btnAgregarAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAspiranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarAspirante)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       _controladorFrm = new ControladorFrmRegistrarIncripciones();
        EscuelaDatos datos= new EscuelaDatos(false, true, true);
        jTableEscuelas.setModel(_controladorFrm.ListarEscuelas(datos));
        
        jLCategorias.setModel(_controladorFrm.ListarCategorias());
        
        jtCompetencias.setModel(_controladorFrm.ListarCompetencias());
        jtCompetencias.getColumnModel().getColumn( 0 ).setCellEditor( new CeldaCheck() );
        jtCompetencias.getColumnModel().getColumn( 0 ).setCellRenderer(new RenderCheck());      

        
        txtBusqueda.addKeyListener(new KeyAdapter() {
                                        @Override
                                        public void keyReleased(final KeyEvent e) 
                                        {
                                            String cadena = txtBusqueda.getText();
                                            txtBusqueda.setText(cadena);
                                            repaint();
                                            filtro();
                                        }
                                    });
        
        
        jTableEscuelas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           
           String nombre = jTableEscuelas.getValueAt(jTableEscuelas.getSelectedRow(), 0).toString();
           
           Escuela escuelita = _controladorFrm.ObtenerEscuelaPorNombre(nombre);
            jtAspirantes.setModel( _controladorFrm.ListarAspirantesPorEscuela(escuelita));
            
           // _controladorFrm.OcultarIdJTable(jtAspirantes);
           
        }
    });
        
        
        
        
                jtAspirantes.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           
           Object dato =  jtAspirantes.getValueAt(jtAspirantes.getSelectedRow(), 0);
           
//           Aspirante aspirante = _controladorFrm.ObtenerAspirante(id);
//           
//           if(aspirante!=null)
//           {
//               if(aspirante.getCategoria()!=null)
//               {
//                        jLCategorias.setSelectedIndex(aspirante.getCategoria().getIdCategoria() -1);
//               }
//              
//           
//           }
           
        }
    });
        
        
    }//GEN-LAST:event_formWindowOpened

    public void filtro() {
        filtro = txtBusqueda.getText();
        trsfiltro.setRowFilter(RowFilter.regexFilter(txtBusqueda.getText(), 0));
    }
   
    
    private void btnAgregarAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAspiranteActionPerformed
       
                // Obtenemos el primer dato del renglon seleccionado
        if (jTableEscuelas.getSelectedRow() != -1) 
        {
              int filaseleccionada = jTableEscuelas.getSelectedRow();
              String nombreEscuela = (String)jTableEscuelas.getValueAt(filaseleccionada, 0);
      
              Escuela escuela = _controladorFrm.ObtenerEscuelaPorNombre(nombreEscuela);
              
              if(escuela!=null )
              {
                    Aspirante entidad = new Aspirante();
                    
                    frmCrubAspirante formulario = new frmCrubAspirante(entidad);
                    formulario.setControlador(_controladorFrm);
                    formulario.setTipoOperacion(1);
                    formulario.setEscuela(escuela);
                    formulario.setFormulario(this);
                    formulario.setVisible(true);
              }

              
              
        }
        else
        {
         JOptionPane.showMessageDialog(null, "Para agregar un aspirante hay que seleccionar una escuela", 
        "Aviso", JOptionPane.OK_OPTION); 
        
        }
        
        
        
        
        
        
        

        
    }//GEN-LAST:event_btnAgregarAspiranteActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        trsfiltro = new TableRowSorter(jTableEscuelas.getModel());
        jTableEscuelas.setRowSorter(trsfiltro);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
                
        
        
        
        int filaseleccionada = jtAspirantes.getSelectedRow();
        
        
        Integer idAspirante = (Integer)jtAspirantes.getValueAt(filaseleccionada, 0);
        
        Aspirante aspirante = _controladorFrm.ObtenerAspirante(idAspirante);
        
        
        
        
        
        List<Competencia> listaCompetencias = null;
        
        DefaultTableModel model = (DefaultTableModel) jtCompetencias.getModel();
  
         for (int i = 0; i < model.getRowCount(); i++) {
             String nombre =   (String) model.getValueAt(i, 1);
            Boolean seleccionado =  (Boolean) model.getValueAt(i, 0);
            
            
            if(seleccionado==true)
            {
                Competencia item = _controladorFrm.ObtenerCompetenciaPorNombre(nombre);
                listaCompetencias.add(item);
            
            }
            
         }
         
         
         if(listaCompetencias!=null && listaCompetencias.size()>0)
         {
         
         
         }
             
             
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarAspirante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JList<String> jLCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableEscuelas;
    private javax.swing.JPanel jpEscuela;
    private javax.swing.JTable jtAspirantes;
    private javax.swing.JTable jtCompetencias;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    @Override
    public void EnviarDatos(Object dato, Integer op) 
    {
        if(op==1)
        {
            Aspirante entidad = (Aspirante) dato;
            
            Boolean respuesta = _controladorFrm.AgregarAspirante(entidad);
        
        }
        else if(op ==2)
        {
        
        
        }
        
        
    }

   


}
